clone_depth: 1
image: Visual Studio 2017
configuration: Release
platform:
    - x64

environment:
    global:
        DESTDIR: C:\pioneer-deps
        CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH="C:\pioneer-deps" -DCMAKE_PREFIX_PATH="C:\pioneer-deps" -DCMAKE_INSTALL_PREFIX="" -DBUILD_SHARED_LIBS=ON -DCMAKE_GENERATOR_TOOLSET="host=x64"

install:
    git submodule update --init --jobs 2

build_script:
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"'

    - cd C:\projects\pioneer-libs\zlib

    - cmake -DCMAKE_BUILD_TYPE:STRING=%CONFIGURATION% %CMAKE_ARGS% .
    - cmake --build . --config %CONFIGURATION% --target INSTALL

    - cd C:\projects\pioneer-libs\libsigc++\MSVC_NMake
    - nmake /f Makefile.vc CFG=release PREFIX=C:\pioneer-deps install

    - cd C:\projects\pioneer-libs\libpng

    - cmake -DCMAKE_BUILD_TYPE:STRING=%CONFIGURATION% %CMAKE_ARGS% -DPNG_STATIC=OFF -DPNG_TESTS=OFF -DPNG_HARDWARE_OPTIMIZATIONS=OFF -DPNG_INTEL_SSE=OFF .
    - cmake --build . --config %CONFIGURATION% --target INSTALL

    - cd C:\projects\pioneer-libs\assimp

    - cmake -DCMAKE_BUILD_TYPE:STRING=%CONFIGURATION% %CMAKE_ARGS% -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_TESTS=OFF -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF -DASSIMP_BUILD_COLLADA_IMPORTER=ON -DASSIMP_BUILD_OBJ_IMPORTER=ON -DASSIMP_BUILD_3MF_IMPORTER=ON .
    - cmake --build . --config %CONFIGURATION% --target INSTALL

    - cd C:\projects\pioneer-libs\curl

    - cmake -DCMAKE_BUILD_TYPE:STRING=%CONFIGURATION% %CMAKE_ARGS% -DBUILD_CURL_EXE=OFF -DHTTP_ONLY=ON -DBUILD_TESTING=OFF .
    - cmake --build . --config %CONFIGURATION% --target INSTALL

    - cd C:\projects\pioneer-libs\libogg

    - cmake -DCMAKE_BUILD_TYPE:STRING=%CONFIGURATION% %CMAKE_ARGS% .
    - cmake --build . --config %CONFIGURATION% --target INSTALL

    - cd C:\projects\pioneer-libs\libvorbis

    - cmake -DCMAKE_BUILD_TYPE:STRING=%CONFIGURATION% %CMAKE_ARGS% .
    - cmake --build . --config %CONFIGURATION% --target INSTALL

    - mkdir C:\projects\pioneer-libs\SDL2\build
    - cd C:\projects\pioneer-libs\SDL2\build

    - cmake -DCMAKE_BUILD_TYPE:STRING=%CONFIGURATION% %CMAKE_ARGS% -DDUMMYAUDIO=OFF -DVIDEO_DUMMY=OFF -DVIDEO_OPENGLES=OFF ..
    - cmake --build . --config %CONFIGURATION% --target INSTALL

    - mkdir C:\projects\pioneer-libs\SDL_image\build
    - cd C:\projects\pioneer-libs\SDL_image\build

    - cmake -DCMAKE_BUILD_TYPE:STRING=%CONFIGURATION% %CMAKE_ARGS% -DENABLE_JPG:BOOL=OFF -DENABLE_TIF:BOOL=OFF ..
    - cmake --build . --config %CONFIGURATION% --target INSTALL

    - mkdir C:\projects\pioneer-libs\freetype2\build
    - cd C:\projects\pioneer-libs\freetype2\build

    - cmake -DCMAKE_BUILD_TYPE:STRING=%CONFIGURATION% %CMAKE_ARGS% ..
    - cmake --build . --config %CONFIGURATION% --target INSTALL

    - copy /B C:\msys64\mingw64\bin\pkg-config.exe C:\pioneer-deps\bin\pkg-config.exe
    - copy /A C:\projects\pioneer-libs\sdl2.pc C:\pioneer-deps\lib\pkgconfig\sdl2.pc
    - copy /A C:\projects\pioneer-libs\SDL2_image.pc C:\pioneer-deps\lib\pkgconfig\SDL2_image.pc

    - cd C:\
    - 7z a "C:\pioneer-deps.zip" "pioneer-deps"
    - appveyor PushArtifact C:\pioneer-deps.zip
