clone_depth: 1

install:
    - C:\msys64\usr\bin\bash -l /c/projects/pioneer-libs/install.sh

build_script:
    - cd C:\
    - 7z a "C:\pioneer-deps.zip" "Pioneer"
    - appveyor PushArtifact C:\pioneer-deps.zip
